"""Render ``data/LICENSES.md`` from the source registry (design 4.2).

    The single `data/LICENSES.md` carries rows for SAM 3 [...], OpenImages
    (CC-BY, attribution columns), SA-1B (research; no redistribution of
    derivatives), GroundingME [...], OpenRef (to be read), COCO-Search18 (no
    commercial use, no redistribution), and the API providers' terms. Releasable
    artefacts, if any: the OpenImages K1 bank only.

Generated rather than hand-written so the file cannot drift from the registry
the download and build code reads.  IDEA-11 shares this file.

    python -m shared.data.licenses            # print
    python -m shared.data.licenses --write    # write to <data root>/LICENSES.md
"""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

from shared import paths
from shared.data.sources import EXTRA_LICENCE_ROWS, PIN, SOURCES


def render() -> str:
    lines = [
        "# Data and model licences",
        "",
        "Generated by `python -m shared.data.licenses` from `shared/data/sources.py`. "
        "One row per asset: licence, locator, date the text was read, allowed uses, "
        "attribution duty. Shared by IDEA-11 and IDEA-91 (design 4.2).",
        "",
        f"Rendered {date.today().isoformat()}.",
        "",
        "## Releasable artefacts",
        "",
        "**The OpenImages K1 bank only** (design P1: CC-BY images make it the only "
        "releasable edited artefact). Every other bank -- anything touching SA-1B, "
        "GroundingME, COCO-Search18 or Ref-L4 -- stays local.",
        "",
        "## Datasets",
        "",
        "| asset | licence | locator | revision | date read | allowed uses | used by | attribution |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for s in SOURCES:
        allowed = ", ".join(s.allowed) if s.allowed else "**unread**"
        lines.append(
            f"| {s.name} | {s.licence} | `{s.locator}` | `{s.revision}` | "
            f"{s.date_read or '**not read**'} | {allowed} | {', '.join(s.used_by)} | "
            f"{s.attribution or '-'} |"
        )
    lines += [
        "",
        "## Models and providers",
        "",
        "| asset | licence | allowed uses | used by |",
        "|---|---|---|---|",
    ]
    for row in EXTRA_LICENCE_ROWS:
        lines.append(
            f"| {row['name']} | {row['licence']} | {row['allowed']} | {row['used_by']} |"
        )

    unread = [s.name for s in SOURCES if not s.allowed or not s.date_read]
    unpinned = [s.name for s in SOURCES if PIN in (s.locator, s.revision)]
    lines += [
        "",
        "## Outstanding",
        "",
        "Licence text not yet read (or read date not recorded):",
        "",
    ]
    lines += [f"- {n}" for n in unread] or ["- none"]
    lines += ["", "Locator or revision not yet pinned:", ""]
    lines += [f"- {n}" for n in unpinned] or ["- none"]
    lines += [
        "",
        "Notes carried from the registry:",
        "",
    ]
    lines += [f"- **{s.name}**: {s.notes}" for s in SOURCES if s.notes]
    return "\n".join(lines) + "\n"


def write(path: Path | None = None) -> Path:
    target = path or (paths.DATA_ROOT / "LICENSES.md")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(), encoding="utf-8")
    return target


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="write to <data root>/LICENSES.md")
    ap.add_argument("--path", type=Path, default=None)
    args = ap.parse_args()
    if args.write or args.path:
        print(f"wrote {write(args.path)}")
    else:
        print(render())


if __name__ == "__main__":
    main()
